### ISSUE TITLE
inject doesn't work with qBittorrent 4.2.5

### ISSUE THREAD

**Issue by KyleSanderson** [mmgoodnow/cross-seed#201] opened 2022-02-27 02:39 UTC
```
verbose: [qbittorrent] Making request to /torrents/properties with body hash=432002781a7022a0fb6131afde310deb
verbose: [qbittorrent] Making request to /torrents/info with body hashes=02101990fa166e03119fdb2c1792e3cf
debug: [qbittorrent] injection failed: The "path" argument must be of type string. Received undefined
error: Found .2020.S02E04.Control.1080p.mkv on FileList - failed to inject, saving instead
verbose: [qbittorrent] Making request to /torrents/properties with body hash=2ffce923e88b94329906f41b1c6c8ec2e2
verbose: [qbittorrent] Making request to /torrents/info with body hashes=02101990fa166e03119fdb2c1792e363f
debug: [qbittorrent] injection failed: The "path" argument must be of type string. Received undefined
error: Found .2020.S02E04.Control.1080p.mkv on TorrentLeech - failed to inject, saving instead
```

Running the latest release, using torznab from jackett. The one major not-expected behaviour thing I noticed was it doesn't actually query the client, but uses the session dir. This is also the case in daemon mode which was rather shocking. It's since been resolved, but the injection still fails with the errors above.

**Comment by mmgoodnow** [comment] 2022-03-01 04:05
I think this is a duplicate of #74

**Closed by mmgoodnow** 2022-03-01 04:05 UTC
