### ISSUE TITLE
404 Not Found errors

### ISSUE THREAD

**Issue by bobokun** [mmgoodnow/cross-seed#177] opened 2021-12-30 14:08 UTC
I'm seeing a lot of `error downloading torrent at  - 404 Not Found` in my recent searches. Is this normal and would it be possible to cache these so next time it searches it will ignore these urls?

**Comment by mmgoodnow** [comment] 2021-12-30 16:19
Hmmm. In 3.0.2 I changed the functionality so that when you get rate limited by your tracker, it will cache the error but retry later. Previously if you were getting rate limited it would just save the error forever. So maybe I should treat 404s and rate limits separately. 

Can you do a little investigation into these listings in jackett that 404 though? In theory if a torrent gets removed from the tracker it should also get removed from the jacket search results

**Comment by bobokun** [comment] 2021-12-30 16:38
I checked a few of the errors and while some of the 404 are not showing up in jackett search, there are several that still show up and I can download the torrent manually through jackett fine. So I'm not sure why cross-seed is having problems downloading it

**Comment by mmgoodnow** [comment] 2021-12-30 20:04
Ultimately, failing to download these urls is pretty harmless though so I wouldn't worry too much about them.

**Comment by mmgoodnow** [comment] 2021-12-30 20:23
Do you see anything in the verbose log from these 404s? There should be two debug logs showing the response and the headers, but they might be not serializing to string properly

**Comment by bobokun** [comment] 2021-12-30 20:36
They all look like this
```json
{
  'content-length': '0',
  connection: 'close',
  date: 'Thu, 30 Dec 2021 09:18:24 GMT',
  server: 'Kestrel',
  'cache-control': 'no-store,no-cache',
  pragma: 'no-cache'
}
```

**Comment by mouzzampk2014** [comment] 2021-12-30 20:58
I'm seeing these too, first I checked the tracker and I can see the torrent is still there. As bobokun already provided the info but if you need further please let me know. Ta

**Comment by mmgoodnow** [comment] 2021-12-30 21:10
gonna close this as a dupe of #38. The changes I made to stop caching those 404s are re-exposing the old bug

**Closed by mmgoodnow** 2021-12-30 21:10 UTC
